version: "3"
services:
  backend:
    build: .
    restart: always
    ports:
      - 8080:8080
    command: ./wait-for-it.sh db:3306 -- mvn spring-boot:run
    depends_on:
      - db
  db:
    image: "mysql:5.7"
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: project_se_db
      MYSQL_ROOT_PASSWORD: root